#!/usr/bin/env node
// tools/city-prices.mjs -- each place's typical home prices and condo fee,
// from HomePilot's own listings (IMPROVEMENT_PLAN.md 3.1a and 3.2).
//
// WHAT IT WRITES
// Only the block in src/cities.js between the "// BEGIN GENERATED by
// tools/city-prices.mjs" line and the "// END GENERATED" line: PT_LISTED and
// CONDO_FEES_LISTED. The hand-typed PT_TYPED and CONDO_FEES_TYPED are never
// touched. Plain code below the block builds PT and CONDO_FEES from
// listed-else-typed, so any place or type this script leaves out keeps its
// typed figure.
//
// THE METHOD (the owner's decision, 2026-09-24)
//   price: the median ASKING price of the place's current listings of that
//          home type x 0.97 (one market-wide sale-to-list ratio), rounded to
//          the nearest $1,000. Only where the place has 10+ such listings.
//   fee:   the median real monthly fee of the place's condo listings. Only
//          where 10+ of them have a usable fee.
//
// WHICH LISTINGS COUNT: exactly the ones the listings page shows. A place name
// is resolved the way the Worker's /listings route resolves it (CITY_ALIASES,
// districtsForRegion and communitiesForCity, into cityMatchClause), and the
// query uses the route's own VISIBLE_LISTING_CLAUSE (PropTx, for sale, active,
// seen in the last 36 hours, $75,000 and up) and SHOWN_HOMES_CLAUSE (the
// home-type allow-list, no land, no life or land lease). The home type comes
// from PROPERTY_TYPE_FILTERS, the clauses behind the listings page's type
// buttons. All of it is imported from workers/homepilot-listings/src, not
// copied, so this script and the listings page cannot drift apart. Condo fees
// go through ldFeeToMonthly() from src/listing-fit.js, the listing pages' own
// function: same frequencies, "One Time" ignored, $10-$5,000 a month.
//
// READ-ONLY. The listings database is read, never written. Every command goes
// through assertSingleSelect(), which refuses anything that is not a single
// SELECT, and a reply in which D1 reports any change stops the run.
//
// KEEPS THE LAST GOOD TABLE. src/cities.js is rewritten only when every query
// succeeded and the result looks sane (most places have listings, every figure
// within bounds, the new file still loads). Otherwise the script exits
// non-zero and the file is left exactly as it was.
//
// Usage, from the repo root (wrangler must be logged in: npx wrangler login):
//   node tools/city-prices.mjs                    query, check, rewrite the block
//   node tools/city-prices.mjs --dry-run          query and print; write nothing
//   node tools/city-prices.mjs --stats out.json   also save every cell's numbers
//   node tools/city-prices.mjs --place Hamilton   one place (repeatable); never writes
// WRANGLER_JS=<path to wrangler/bin/wrangler.js> overrides where wrangler is
// found (default: node_modules/wrangler in this folder or any folder above it).

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  VISIBLE_LISTING_CLAUSE, SHOWN_HOMES_CLAUSE, PROPERTY_TYPE_FILTERS,
  MIN_LISTING_PRICE, MAX_LISTING_AGE_HOURS, cityMatchClause, freshnessCutoffIso,
} from "../workers/homepilot-listings/src/db.js";
import { CITY_ALIASES, PUBLIC_CITY_NAMES } from "../workers/homepilot-listings/src/cities.js";
import { districtsForRegion } from "../workers/homepilot-listings/src/toronto-districts.js";
import { communitiesForCity } from "../workers/homepilot-listings/src/communities.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CITIES_JS = path.join(ROOT, "src", "cities.js");
const LISTING_FIT_JS = path.join(ROOT, "src", "listing-fit.js");
// wrangler runs here so it finds wrangler.jsonc and its D1 binding.
const WORKER_DIR = path.join(ROOT, "workers", "homepilot-listings");
const DATABASE = "homepilot-listings-db";

const SALE_TO_LIST = 0.97;
const MIN_LISTINGS = 10;
const MIN_FEES = 10;
// PT's own key order, and the order of the derived-type CASE in db.js.
const TYPES = ["condo", "town", "semi", "detached"];

// A run that falls outside these writes nothing.
const MIN_SHARE_OF_PLACES_WITH_LISTINGS = 0.8;
const MAX_PRICE = 10_000_000;
const FEE_BOUNDS = [10, 5000]; // ldFeeToMonthly()'s own bounds, checked again

const QUERY_TIMEOUT_MS = 180_000;
const CONCURRENCY = 3;

const BEGIN = "// BEGIN GENERATED by tools/city-prices.mjs";
const END = "// END GENERATED";

// A refused command, or D1 reporting a change. Never retried: it stops the run.
class StopError extends Error {}

// ── The query ──

// The home type of a row, exactly as db.js labels it for the listings page.
// db.js's buildDerivedTypeCase() is not exported; this is the same CASE over
// the same exported PROPERTY_TYPE_FILTERS, which are mutually exclusive. NULL
// is a shown home with no type button (Duplex ... Multiplex): no type's price.
const HOME_TYPE_CASE =
  `CASE ${TYPES.map((t) => `WHEN ${PROPERTY_TYPE_FILTERS[t]} THEN '${t}'`).join(" ")} ELSE NULL END`;

// The SELECT for one place: the /listings route's own place resolution and
// the WHERE clause of getListingsByCity() in db.js. The route's paging, budget,
// bedroom and sort options are left out: they narrow what one buyer is shown,
// not what the place has.
export function placeQuery(place, cutoffIso) {
  const city = CITY_ALIASES[place] || place;
  const match = cityMatchClause(city, districtsForRegion(place), communitiesForCity(place));
  // subtype is only reported (--stats), so a reader can see what a median is made of.
  const sql =
    `SELECT list_price, TRIM(property_subtype) AS subtype, ${HOME_TYPE_CASE} AS home_type, ` +
    `association_fee, association_fee_frequency ` +
    `FROM listings WHERE ${match.sql} AND ${VISIBLE_LISTING_CLAUSE} AND ${SHOWN_HOMES_CLAUSE}`;
  // `wrangler d1 execute` takes no bind parameters, so they are written into
  // the SQL as literals, in getListingsByCity()'s order: the place's own binds,
  // then the freshness cutoff.
  return inlineBinds(sql, [...match.binds, cutoffIso]);
}

function sqlLiteral(value) {
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  throw new Error(`Cannot write ${String(value)} into SQL`);
}

// Replaces each ? outside a string literal with the next value, and insists
// the counts match.
export function inlineBinds(sql, binds) {
  let out = "";
  let used = 0;
  let inString = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    if (inString) {
      out += c;
      if (c === "'") {
        if (sql[i + 1] === "'") { out += "'"; i++; } else inString = false;
      }
    } else if (c === "'") {
      inString = true;
      out += c;
    } else if (c === "?") {
      if (used >= binds.length) throw new Error("More placeholders than values");
      out += sqlLiteral(binds[used++]);
    } else {
      out += c;
    }
  }
  if (used !== binds.length) throw new Error(`${binds.length} values for ${used} placeholders`);
  return out;
}

// Words that would make a statement do anything but read.
const WRITE_WORDS = /\b(INSERT|UPDATE|DELETE|REPLACE|UPSERT|MERGE|CREATE|DROP|ALTER|ATTACH|DETACH|PRAGMA|VACUUM|REINDEX|ANALYZE|BEGIN|COMMIT|ROLLBACK|SAVEPOINT|RELEASE|TRUNCATE|RETURNING|INTO)\b/i;

// Refuses anything that is not one single SELECT. String literals are blanked
// out first, so a quoted phrase can neither hide a second statement nor trip
// the check. No semicolons, comments or quoted names at all.
export function assertSingleSelect(sql) {
  if (typeof sql !== "string" || !sql.trim()) throw new StopError("Refusing to run an empty command.");
  let skeleton = "";
  let inString = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    if (inString) {
      if (c === "'") {
        if (sql[i + 1] === "'") i++; // '' is a quote inside the literal
        else { inString = false; skeleton += c; }
      } else {
        skeleton += " ";
      }
      continue;
    }
    if (c === "'") inString = true;
    skeleton += c;
  }
  if (inString) throw new StopError("Refusing to run: a string literal is not closed.");
  if (/;|--|\/\*|"|`|\[/.test(skeleton)) {
    throw new StopError("Refusing to run: only one plain SELECT is allowed (found ; -- /* or a quoted name).");
  }
  if (!/^\s*SELECT\s/i.test(skeleton)) throw new StopError("Refusing to run: the command is not a SELECT.");
  const word = skeleton.match(WRITE_WORDS);
  if (word) throw new StopError(`Refusing to run: "${word[1]}" is not allowed; this script only reads.`);
  return sql;
}

// ── Running it ──

function findWrangler() {
  if (process.env.WRANGLER_JS) return process.env.WRANGLER_JS;
  for (let dir = ROOT; ; dir = path.dirname(dir)) {
    const candidate = path.join(dir, "node_modules", "wrangler", "bin", "wrangler.js");
    if (fs.existsSync(candidate)) return candidate;
    if (path.dirname(dir) === dir) throw new Error("wrangler not found: run npm install, or set WRANGLER_JS.");
  }
}

// wrangler normally prints only the JSON; tolerate a notice printed before it.
function parseD1Reply(stdout) {
  let reply = null;
  for (let at = 0; reply === null && at !== -1; at = stdout.indexOf("\n[", at + 1)) {
    try { reply = JSON.parse(stdout.slice(at)); } catch { /* try the next line that opens with [ */ }
  }
  if (!Array.isArray(reply) || reply.length !== 1) throw new Error("wrangler did not return one JSON result");
  const result = reply[0];
  if (!result || result.success !== true || !Array.isArray(result.results)) throw new Error("D1 reported a failed query");
  const meta = result.meta || {};
  if (meta.changed_db || meta.changes || meta.rows_written) {
    throw new StopError("D1 reports a change to the database. Stopping: this script only reads.");
  }
  return { rows: result.results, rowsRead: Number(meta.rows_read) || 0 };
}

// One read-only query. Node runs wrangler's own JS entry point directly, with
// no shell in between, so the SQL reaches wrangler as one untouched argument.
function d1Select(wranglerJs, sql) {
  assertSingleSelect(sql);
  return new Promise((resolve, reject) => {
    const child = spawn(
      process.execPath,
      [wranglerJs, "d1", "execute", DATABASE, "--remote", "--json", "--command", sql],
      { cwd: WORKER_DIR, windowsHide: true, env: { ...process.env, WRANGLER_SEND_METRICS: "false" } },
    );
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (d) => { stdout += d; });
    child.stderr.on("data", (d) => { stderr += d; });
    const timer = setTimeout(() => child.kill(), QUERY_TIMEOUT_MS);
    child.on("error", (e) => { clearTimeout(timer); reject(e); });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code !== 0) {
        const lines = (stderr || stdout).split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
        const detail = lines.find((l) => /error|✘/i.test(l)) || lines.slice(-3).join(" ");
        reject(new Error(`wrangler exited with ${code}: ${detail}`));
        return;
      }
      try { resolve(parseD1Reply(stdout)); } catch (e) { reject(e); }
    });
  });
}

async function d1SelectOrRetry(wranglerJs, sql, label) {
  try {
    return await d1Select(wranglerJs, sql);
  } catch (e) {
    if (e instanceof StopError) throw e;
    log(`  ${label}: ${e.message} -- trying once more`);
    await new Promise((r) => setTimeout(r, 5000));
    return d1Select(wranglerJs, sql);
  }
}

// ── The numbers ──

function median(sorted) {
  const n = sorted.length;
  if (!n) return null;
  const mid = Math.floor(n / 2);
  return n % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

// Linear-interpolation percentile, for the --stats file only.
function percentile(sorted, p) {
  if (!sorted.length) return null;
  const at = (sorted.length - 1) * p;
  const lo = Math.floor(at);
  const hi = Math.ceil(at);
  return sorted[lo] + (sorted[hi] - sorted[lo]) * (at - lo);
}

export function summarizePlace(rows, feeToMonthly) {
  const prices = Object.fromEntries(TYPES.map((t) => [t, []]));
  const bySubtype = Object.fromEntries(TYPES.map((t) => [t, {}])); // PropTx label -> prices
  const fees = [];
  const feeRejected = {}; // frequency as sent -> count: a fee given, but not usable
  let feeMissing = 0;
  let noType = 0;
  for (const row of rows) {
    const price = Number(row.list_price);
    if (!TYPES.includes(row.home_type) || !Number.isFinite(price)) { noType++; continue; }
    prices[row.home_type].push(price);
    const label = String(row.subtype ?? "(none)");
    (bySubtype[row.home_type][label] ||= []).push(price);
    if (row.home_type !== "condo") continue;
    const fee = feeToMonthly(row.association_fee, row.association_fee_frequency);
    if (fee) {
      fees.push(fee);
    } else if (!(Number(row.association_fee) > 0)) {
      feeMissing++;
    } else {
      const f = String(row.association_fee_frequency ?? "(none)");
      feeRejected[f] = (feeRejected[f] || 0) + 1;
    }
  }
  const types = {};
  for (const t of TYPES) {
    const s = prices[t].sort((a, b) => a - b);
    const mid = median(s);
    types[t] = {
      n: s.length,
      median: mid,
      p25: percentile(s, 0.25),
      p75: percentile(s, 0.75),
      low: s.length ? s[0] : null,
      high: s.length ? s[s.length - 1] : null,
      price: s.length >= MIN_LISTINGS ? Math.round((mid * SALE_TO_LIST) / 1000) * 1000 : null,
      subtypes: Object.fromEntries(Object.entries(bySubtype[t]).map(([label, list]) => {
        const sorted = list.sort((a, b) => a - b);
        return [label, { n: sorted.length, median: median(sorted) }];
      })),
    };
  }
  fees.sort((a, b) => a - b);
  const feeMid = median(fees);
  return {
    total: rows.length,
    noType,
    types,
    fees: {
      n: fees.length,
      median: feeMid,
      p25: percentile(fees, 0.25),
      p75: percentile(fees, 0.75),
      fee: fees.length >= MIN_FEES ? Math.round(feeMid) : null,
      missing: feeMissing,
      rejected: feeRejected,
    },
  };
}

// ── The app's own files ──

function loadCities(text = fs.readFileSync(CITIES_JS, "utf8")) {
  return vm.runInContext(
    `${text}\n;({ M, PT, PT_SOURCE, PT_TYPED, CONDO_FEES, CONDO_FEES_TYPED })`,
    vm.createContext({}),
    { filename: "cities.js" },
  );
}

function loadFeeToMonthly() {
  const context = vm.createContext({});
  vm.runInContext(fs.readFileSync(LISTING_FIT_JS, "utf8"), context, { filename: "listing-fit.js" });
  const fn = vm.runInContext("typeof ldFeeToMonthly === 'function' ? ldFeeToMonthly : null", context);
  if (!fn) throw new Error("src/listing-fit.js no longer defines ldFeeToMonthly()");
  return fn;
}

function renderBlock(run, results, eol) {
  const lines = [
    `${BEGIN} -- do not edit by hand; run \`node tools/city-prices.mjs\`.`,
    `// Run ${run.date} on the live listings: those updated since ${run.listingsSince}, the`,
    `// listings page's own ${MAX_LISTING_AGE_HOURS}-hour window. price = median asking price of the place's`,
    `// listings of that type x ${SALE_TO_LIST}, to the nearest $1,000, only where it has ${MIN_LISTINGS}+ of them.`,
    `// fee = median real monthly fee of the place's condo listings, only where ${MIN_FEES}+ have one.`,
    "// n = listings (or fees) behind the figure. A place or type left out keeps its typed figure.",
    `const CITY_PRICES_RUN=${JSON.stringify(run)};`,
    "const PT_LISTED={",
  ];
  for (const r of results) {
    const cells = TYPES.filter((t) => r.summary.types[t].price !== null)
      .map((t) => `${t}:{price:${r.summary.types[t].price},n:${r.summary.types[t].n}}`);
    if (cells.length) lines.push(`  ${JSON.stringify(r.place)}:{${cells.join(",")}},`);
  }
  lines.push("};", "const CONDO_FEES_LISTED={");
  for (const r of results) {
    const f = r.summary.fees;
    if (f.fee !== null) lines.push(`  ${JSON.stringify(r.place)}:{fee:${f.fee},n:${f.n}},`);
  }
  lines.push("};", END);
  return lines.join(eol);
}

function replaceBlock(text, block) {
  if (text.split(BEGIN).length !== 2 || text.split(END).length !== 2) {
    throw new Error(`src/cities.js must hold exactly one "${BEGIN}" and one "${END}" line`);
  }
  const start = text.indexOf(BEGIN);
  const stop = text.indexOf(END, start);
  if (stop < 0) throw new Error(`"${END}" comes before "${BEGIN}" in src/cities.js`);
  return text.slice(0, start) + block + text.slice(stop + END.length);
}

// ── Checks before anything is written ──

function checkRun(results) {
  const problems = [];
  const failed = results.filter((r) => r.error);
  if (failed.length) problems.push(`${failed.length} queries failed: ${failed.map((r) => `${r.place} (${r.error})`).join("; ")}`);
  const withRows = results.filter((r) => r.summary && r.summary.total > 0).length;
  const needed = Math.ceil(results.length * MIN_SHARE_OF_PLACES_WITH_LISTINGS);
  if (withRows < needed) {
    problems.push(`only ${withRows} of ${results.length} places have any listings (at least ${needed} expected); is the ingest running?`);
  }
  for (const r of results.filter((x) => x.summary)) {
    for (const t of TYPES) {
      const p = r.summary.types[t].price;
      if (p !== null && !(p >= MIN_LISTING_PRICE && p <= MAX_PRICE)) problems.push(`${r.place} ${t}: price ${p} out of bounds`);
    }
    const fee = r.summary.fees.fee;
    if (fee !== null && !(fee >= FEE_BOUNDS[0] && fee <= FEE_BOUNDS[1])) problems.push(`${r.place}: condo fee ${fee} out of bounds`);
  }
  return problems;
}

function checkNewFile(text, places) {
  let got;
  try {
    got = loadCities(text);
  } catch (e) {
    throw new Error(`the new src/cities.js does not load: ${e.message}`);
  }
  for (const place of places) {
    const row = got.PT[place];
    if (!row) throw new Error(`the new PT has no ${place}`);
    for (const t of TYPES) {
      const v = row[t];
      if (!(t in row) || (v !== null && !(v >= MIN_LISTING_PRICE && v <= MAX_PRICE))) {
        throw new Error(`the new PT has a bad ${place} ${t}: ${v}`);
      }
    }
  }
  if (!got.M.every((m) => got.PT[m.n])) throw new Error("a place in M has no PT row");
}

// ── Output ──

function log(line) {
  process.stderr.write(`${line}\n`);
}

const money = (v) => (v === null || v === undefined ? "none" : `$${Math.round(v).toLocaleString("en-CA")}`);

function printSummary(results, cities) {
  for (const r of results) {
    if (r.error) { console.log(`${r.place}: FAILED (${r.error})`); continue; }
    const s = r.summary;
    const parts = TYPES.map((t) => {
      const c = s.types[t];
      const typed = cities.PT_TYPED[r.place] ? cities.PT_TYPED[r.place][t] : null;
      return c.price !== null
        ? `${t} ${c.n}: ${money(c.price)} (typed ${money(typed)})`
        : `${t} ${c.n}: keeps typed ${money(typed)}`;
    });
    const typedFee = cities.CONDO_FEES_TYPED[r.place];
    parts.push(s.fees.fee !== null
      ? `fee ${s.fees.n}: ${money(s.fees.fee)} (typed ${money(typedFee)})`
      : `fee ${s.fees.n}: keeps typed ${money(typedFee)}`);
    console.log(`${r.place} [${s.total} listings]: ${parts.join(" | ")}`);
  }
}

function parseArgs(argv) {
  const args = { dryRun: false, stats: null, places: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--dry-run") args.dryRun = true;
    else if (a === "--stats" && argv[i + 1]) args.stats = argv[++i];
    else if (a === "--place" && argv[i + 1]) args.places.push(argv[++i]);
    else throw new Error(`Unknown argument: ${a}`);
  }
  return args;
}

async function mapPool(items, limit, fn) {
  const out = new Array(items.length);
  let next = 0;
  let stop = null;
  const worker = async () => {
    while (!stop && next < items.length) {
      const i = next++;
      try {
        out[i] = await fn(items[i], i);
      } catch (e) {
        stop = e;
      }
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  if (stop) throw stop;
  return out;
}

async function main() {
  let args;
  try {
    args = parseArgs(process.argv.slice(2));
  } catch (e) {
    log(e.message);
    return 2;
  }
  const cities = loadCities();
  const feeToMonthly = loadFeeToMonthly();
  const allPlaces = [...new Set(cities.M.map((m) => m.n))];
  const unknown = args.places.filter((p) => !allPlaces.includes(p));
  if (unknown.length) {
    log(`Not a place in src/cities.js: ${unknown.join(", ")}`);
    return 2;
  }
  const places = args.places.length ? args.places : allPlaces;
  const writes = !args.dryRun && !args.places.length;
  const wranglerJs = findWrangler();

  // The same 36-hour cutoff the live /listings route computes for a request,
  // taken once so every place is read against the same moment.
  const now = Date.now();
  const cutoff = freshnessCutoffIso(now);
  log(`Reading ${places.length} places from ${DATABASE} (read-only): listings updated since ${cutoff}`);

  let done = 0;
  const results = await mapPool(places, CONCURRENCY, async (place) => {
    const base = {
      place,
      city: CITY_ALIASES[place] || place,
      districts: districtsForRegion(place),
      communities: communitiesForCity(place),
    };
    if (!PUBLIC_CITY_NAMES.includes(place)) {
      // /listings answers 400 for this name, so the site shows it no listings.
      log(`  ${place}: not a name /listings accepts; no listings counted`);
      return { ...base, skipped: true, sql: null, rowsRead: 0, summary: summarizePlace([], feeToMonthly) };
    }
    const sql = placeQuery(place, cutoff);
    try {
      const { rows, rowsRead } = await d1SelectOrRetry(wranglerJs, sql, place);
      done++;
      log(`  [${done}/${places.length}] ${place}: ${rows.length} listings (D1 rows read: ${rowsRead})`);
      return { ...base, sql, rowsRead, summary: summarizePlace(rows, feeToMonthly) };
    } catch (e) {
      if (e instanceof StopError) throw e;
      done++;
      log(`  [${done}/${places.length}] ${place}: FAILED -- ${e.message}`);
      return { ...base, sql, error: e.message };
    }
  });

  printSummary(results, cities);
  const rowsRead = results.reduce((sum, r) => sum + (r.rowsRead || 0), 0);
  log(`D1 rows read in total: ${rowsRead}`);

  const run = {
    date: new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto" }).format(new Date(now)),
    asOf: new Date(now).toISOString(),
    listingsSince: cutoff,
    saleToList: SALE_TO_LIST,
    minListings: MIN_LISTINGS,
    minFees: MIN_FEES,
  };

  if (args.stats) {
    const stats = {
      run: { ...run, database: DATABASE, rowsRead },
      places: results.map((r) => ({
        ...r,
        typed: cities.PT_TYPED[r.place] || null,
        typedFee: cities.CONDO_FEES_TYPED[r.place] ?? null,
      })),
    };
    fs.writeFileSync(path.resolve(args.stats), `${JSON.stringify(stats, null, 2)}\n`);
    log(`Numbers for every place and type saved to ${path.resolve(args.stats)}`);
  }

  const problems = checkRun(results);
  if (problems.length) {
    log("\nNOT WRITTEN -- src/cities.js is unchanged. Problems:");
    for (const p of problems) log(`  - ${p}`);
    return 1;
  }
  if (!writes) {
    log("\nDry run: src/cities.js not written.");
    return 0;
  }

  const oldText = fs.readFileSync(CITIES_JS, "utf8");
  const eol = oldText.includes("\r\n") ? "\r\n" : "\n";
  const newText = replaceBlock(oldText, renderBlock(run, results, eol));
  checkNewFile(newText, places);
  const tmp = `${CITIES_JS}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, newText);
  fs.renameSync(tmp, CITIES_JS);
  const cells = results.reduce((sum, r) => sum + TYPES.filter((t) => r.summary.types[t].price !== null).length, 0);
  const fees = results.filter((r) => r.summary.fees.fee !== null).length;
  log(`\nsrc/cities.js updated: ${cells} prices and ${fees} condo fees from listings; everything else keeps its typed figure.`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().then(
    (code) => { process.exitCode = code; },
    (e) => {
      log(`\nNOT WRITTEN -- src/cities.js is unchanged. ${e instanceof StopError ? "Stopped" : "Failed"}: ${e.message}`);
      process.exitCode = 1;
    },
  );
}
